export const PROPOSAL_REPOSITORY = Symbol('PROPOSAL_REPOSITORY');
export const ASSIGNMENT_REPOSITORY = Symbol('ASSIGNMENT_REPOSITORY');
export const CHAIN_TRANSACTION_REPOSITORY = Symbol(
  'CHAIN_TRANSACTION_REPOSITORY',
);
export const GOVERNANCE_GATEWAY = Symbol('GOVERNANCE_GATEWAY');
export const VOTE_REPOSITORY = Symbol('VOTE_REPOSITORY');
export const SYNC_STATE_REPOSITORY = Symbol('SYNC_STATE_REPOSITORY');
export const OPERATIONAL_DATABASE = Symbol('OPERATIONAL_DATABASE');
