import { MultiAgentSystem } from '../agents/multi-agent.system';

const config=(values:Record<string,unknown>={})=>({get:(key:string,fallback:unknown)=>values[key]??fallback}) as any;
function registry(failRag=false){return {invoke:jest.fn(async (_agent:string,name:string,args:any)=>{const startedAt=new Date().toISOString();let result:any={};if(name==='getProposal')result={id:args.proposalId,on_chain_id:'12',title:'Test proposal',status:'FINALIZED',starts_at:new Date('2025-01-01'),ends_at:new Date('2026-01-01'),members:[]};if(name==='getProposalVotes')result={count:2,totalVotingPower:2,evidenceIds:['event:vote:1','event:vote:2'],votes:[]};if(name==='getProposalTimeline')result={events:[],evidenceIds:['event:finalized']};if(name==='vectorSearch'){if(failRag)throw new Error('RAG unavailable');result=[{chunkEvidenceId:'chunk:1',artefactEvidenceId:'artefact:1',proposalId:'12',content:'Risk of treasury loss',score:.9}]};if(name==='calculateQuorum')result={ruleId:'GOV-01',result:'PASS',inputs:{totalVotingPower:2,requiredVotes:2},evidenceIds:['event:vote:1','event:vote:2']};if(name==='getProposalEvidence')result={evidenceIds:['event:vote:1']};if(name==='getEvidenceById')result={evidenceId:args.evidenceId,valid:true,sourceType:'governance-event',proposalId:'12'};return {result,call:{tool:name,arguments:args,startedAt,status:'success',latencyMs:1}};})} as any;}
const ollama=(content:string)=>({chat:jest.fn().mockResolvedValue({content,latencyMs:1,inputTokens:5,outputTokens:5}),getChatModel:()=> 'qwen3.5:4b'}) as any;

describe('MultiAgentSystem',()=>{
  it('routes a factual vote count only to SQL without an LLM call',async()=>{const r=registry(),o=ollama('');const system=new MultiAgentSystem(r,o,config());const out=await system.execute({question:'How many votes did proposal 12 receive?',proposalId:'12'});expect(out.answer).toContain('2 votes');expect(out.agentsUsed).toContain('sql');expect(out.agentsUsed).not.toContain('rag');expect(o.chat).not.toHaveBeenCalled();});
  it('routes a selected-proposal overview through SQL and RAG',async()=>{const r=registry(),o=ollama('{"answer":"The document identifies treasury loss.","claims":[{"text":"Treasury loss is identified.","type":"SEMANTIC","evidenceIds":["chunk:1"]}]}');const out=await new MultiAgentSystem(r,o,config()).execute({question:'I need information about this proposal',proposalId:'12',localProposalId:'12',onChainProposalId:'12'});expect(out.toolsUsed).toEqual(expect.arrayContaining(['getProposal','getProposalVotes','getProposalTimeline','vectorSearch']));expect(out.agentsUsed).toEqual(expect.arrayContaining(['sql','rag','synthesis','verification']));});
  it('maps timeline and eligibility phrases to their deterministic tools',async()=>{const r=registry(),o=ollama('{"answer":"The evidence was checked.","claims":[{"text":"The evidence was checked.","type":"FACTUAL","evidenceIds":["event:finalized"]}]}');const system=new MultiAgentSystem(r,o,config());const timeline=await system.execute({question:'When did voting end for proposal 12?',proposalId:'12'});expect(timeline.toolsUsed).toContain('getProposalTimeline');const eligible=await system.execute({question:'Is 0x1111111111111111111111111111111111111111 eligible for proposal 12?',proposalId:'12'});expect(eligible.toolsUsed).toContain('checkMemberEligibility');});
  it('returns the supplied scope conflict without invoking tools',async()=>{const r=registry();const out=await new MultiAgentSystem(r,ollama(''),config()).execute({question:'Tell me about proposal 12',proposalId:'onchain-4',scopeConflict:'Your selected proposal is #4 but your question refers to #12. Please choose one.'});expect(out.answer).toBe('Your selected proposal is #4 but your question refers to #12. Please choose one.');expect(out.toolsUsed).toEqual([]);expect(r.invoke).not.toHaveBeenCalled();});
  it('requires scope for contextual proposal language',async()=>{const r=registry();const out=await new MultiAgentSystem(r,ollama(''),config()).execute({question:'Tell me about this proposal'});expect(out.answer).toBe('Select a proposal scope before asking about this proposal.');expect(r.invoke).not.toHaveBeenCalled();});
  it('returns structured overview facts when the selected proposal has no document chunks',async()=>{const r=registry();r.invoke.mockImplementation(async (_agent:string,name:string,args:any)=>{const base=await registry().invoke(_agent,name,args);if(name==='vectorSearch')return {...base,result:[]};return base;});const out=await new MultiAgentSystem(r,ollama(''),config()).execute({question:'Tell me about this proposal',proposalId:'12',localProposalId:'12',onChainProposalId:'12'});expect(out.answer).toContain('Test proposal');expect(out.answer).toContain('No indexed document evidence was found');expect(out.toolsUsed).toEqual(expect.arrayContaining(['getProposal','getProposalVotes','getProposalTimeline','vectorSearch']));expect(out.abstained).toBe(false);});
  it('routes semantic questions to RAG, synthesis, and verification',async()=>{const r=registry(),o=ollama('{"answer":"Treasury loss is a risk [chunk:1].","claims":[{"text":"Treasury loss is a risk.","type":"SEMANTIC","evidenceIds":["chunk:1"]}]}');const out=await new MultiAgentSystem(r,o,config()).execute({question:'What risks are discussed in proposal 12?',proposalId:'12'});expect(out.agentsUsed).toEqual(expect.arrayContaining(['rag','synthesis','verification']));expect(out.verification.status).toBe('SUPPORTED');});
  it('runs deterministic compliance for quorum',async()=>{const r=registry(),o=ollama('{"answer":"Quorum passed.","claims":[{"text":"GOV-01 result is PASS.","type":"COMPLIANCE","evidenceIds":["event:vote:1"]}]}');const out=await new MultiAgentSystem(r,o,config()).execute({question:'Did proposal 12 satisfy quorum?',proposalId:'12'});expect(out.agentsUsed).toEqual(expect.arrayContaining(['sql','compliance']));expect(out.toolsUsed).toContain('calculateQuorum');});
  it('routes temporal eligibility questions to SQL and compliance',async()=>{const r=registry(),o=ollama('{"answer":"The vote was within the window.","claims":[]}');const out=await new MultiAgentSystem(r,o,config()).execute({question:'Did member 0x1111111111111111111111111111111111111111 vote before voting ended for proposal 12?',proposalId:'12'});expect(out.agentsUsed).toEqual(expect.arrayContaining(['sql','compliance']));expect(out.toolsUsed).toContain('checkVotingWindow');});
  it('runs SQL, RAG, and compliance for a mixed finalization question',async()=>{const r=registry(),o=ollama('{"answer":"Finalized and quorum passed.","claims":[{"text":"GOV-01 result is PASS.","type":"COMPLIANCE","evidenceIds":["event:vote:1"]}]}');const out=await new MultiAgentSystem(r,o,config()).execute({question:'Why was proposal 12 finalized and did it satisfy quorum?',proposalId:'12'});expect(out.agentsUsed).toEqual(expect.arrayContaining(['sql','rag','compliance']));});
  it('routes blockchain proof to SQL and provenance',async()=>{const out=await new MultiAgentSystem(registry(),ollama(''),config()).execute({question:'What blockchain evidence proves this vote for proposal 12?',proposalId:'12'});expect(out.agentsUsed).toEqual(expect.arrayContaining(['sql','provenance']));});
  it('abstains on unsupported questions',async()=>{const out=await new MultiAgentSystem(registry(),ollama(''),config()).execute({question:'What is the weather?'});expect(out.abstained).toBe(true);});
  it('handles required RAG failure with controlled abstention',async()=>{const out=await new MultiAgentSystem(registry(true),ollama(''),config()).execute({question:'Explain risks in proposal 12',proposalId:'12'});expect(out.abstained).toBe(true);expect(out.errors[0]).toContain('RAG unavailable');});
  it('enforces the maximum plan size',async()=>{const system=new MultiAgentSystem(registry(),ollama(''),config({MAX_AGENT_STEPS:1}));await expect(system.execute({question:'Why was proposal 12 finalized and did it satisfy quorum?',proposalId:'12'})).rejects.toThrow('MAX_AGENT_STEPS');});
});
